apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
    - name: example-container
      image: registry.k8s.io/busybox
      command: ["/bin/sh", "-c", "cat /etc/config/SPECIAL_TYPE"]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: special-config